# Generated by Django 6.0 on 2025-12-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
