# Generated by Django 6.0 on 2025-12-14 01:52

from django.db import migrations ,models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_year'),
    ]

    operations = [
        migrations.AddField(model_name='listing',name='title',field=models.CharField(max_length=100),),
    ]
