# Generated by Django 6.0 on 2025-12-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_listing_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='year',
        ),
    ]
