# Generated by Django 6.0 on 2025-12-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_band_like_new_remove_listing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
