# Generated by Django 6.0 on 2025-12-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='years',
            new_name='year',
        ),
    ]
