# Generated by Django 6.0 on 2025-12-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_rename_years_listing_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='year',
            field=models.IntegerField(blank=True, default=2004, null=True),
        ),
    ]
