# Generated by Django 6.0 on 2025-12-18 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_alter_listing_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='year',
        ),
    ]
